### ISSUE TITLE
Unable to use compare operator between two strings

### ISSUE THREAD

**Issue by amarendravanipenta** [zzzprojects/Z.Expressions.Eval#116]
I have been trying to evaluate an expression of string comparison. But I was getting a run time error. Below is the snippet of the compiler with the error.

For Numeric:

![image](https://user-images.githubusercontent.com/71650921/135283627-20822751-f30d-41c5-8773-cf5f40ca83f9.png)

For Strings : 

![image](https://user-images.githubusercontent.com/71650921/135283763-31e01f7c-3e19-4c14-b257-75bc5d4714a4.png)

We are able to compare numeric or boolean values. But not the strings. Is there any way to do that or the error was as expected?

Any response would be appreciated.

Thanks,
Amarendra.

**Comment by JonathanMagnan** [comment]
Sure we can compare easily string: https://dotnetfiddle.net/kONyU0

But in your example, your “female” is currently not considered a string but a variable since there is no quote. So that’s why you get the current error.

So that’s possible, but only if you let our library know that your string is a string 😉

Let me know if that answers correctly to your request.

Best Regards,

Jon

**Comment by amarendravanipenta** [comment]
Perfect!
Thanks for the quick assistance.
