### ISSUE TITLE
Mono Support?

### ISSUE THREAD

**Issue by softwaretirol** [zzzprojects/Z.Expressions.Eval#13]
If i try to run a Console application with the following statement:
"var func = Z.Expressions.Eval.Compile("1+2");"

I am getting an Exception:

System.TypeInitializationException: The type initializer for 'Z.Expressions.EvalManager' threw an exception. ---> System.TypeLoadException: Could not resolve type with token 010000bb
  at Z.Expressions.EvalContext..ctor () [0x0007a] in <30ed86fefe7e4b81af44bca0ad083405>:0 
  at Z.Expressions.EvalManager..cctor () [0x0000a] in <30ed86fefe7e4b81af44bca0ad083405>:0 
   --- End of inner exception stack trace ---
  at Z.Expressions.Eval.Compile (System.String code) [0x00000] in <30ed86fefe7e4b81af44bca0ad083405>:0 
  at MDebugConsoleApp5.Program.Main (System.String[] args) [0x00002] 

Do you see the possibilities to support Mono?

**Comment by JonathanMagnan** [comment]
Hello @softwaretirol ,

Unfortunately, we have no plan to support `Mono` however we already support `.NET Standard`.

We already tried previously to support `Mono`, however, there is too much small thing that's different.

To be honest, I don't think the support for this platform will never happen.

I still added this request to our pool list.

Let me know if we can close this issue since as I said, we currently have no short or long-term plan to support it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @softwaretirol ,

We will close this request since I don't think we will ever support `Mono`.

This request will stay open on our `pool` list whoever.
Best Regards,

Jonathan
