### ISSUE TITLE
Version Update 

### ISSUE THREAD

**Issue by Sambu-ivy** [zzzprojects/Z.Expressions.Eval#149]
Hi,

We use Eval dll in our C# project. There is a strange issue that happens whenever there is a new version update available for download.
The Eval throws System.FormatException in runtime whenever the current version does not match the latest version available in Nuget  and the only way to fix it is to update the Eval dll to the latest version from Nuget package manager and the error is gone.

Does Eval compare the current and latest version at runtime?

Thanks,
Sambu

**Comment by JonathanMagnan** [comment]
Hello @Sambu-ivy ,

Our library doesn't use the internet or is not aware at all if a new NuGet package has been released or not.

We might be wrong, but here we believe is happening: You currently use our library in a way that requires a license ([free with less than 50 characters or using LINQ methods](https://eval-expression.net/overview#is-c-eval-expression-free). So at the beginning of every month, your trial expires, and you download the latest version that contains a trial for the month.

We usually release this library once or twice a month, so it could explain why you believe this is due to a new version available.

So if we are right, the recommended solution would be to buy a license: https://eval-expression.net/pricing

Let me know if that was the cause of this error.

Best Regards,

Jon

**Comment by Sambu-ivy** [comment]
Hi,

Thank you for your reply. Looks like we do not have a licensed version, I could not find the license key in the config files.

Regards,
Sambu


Regards,
Sambu
