### ISSUE TITLE
Calculator basic math

### ISSUE THREAD

**Issue by papyr** [zzzprojects/Z.Expressions.Eval#96]
I am trying to do something for a kids website, the students want to build formulas from the UI in the web page and then save those. So, that they can apply those on a set of excel or csv sheets.

Feature request, if you have a calculator for this it would gain a lot of traction

**Comment by JonathanMagnan** [comment]
Hello @papyr ,

What exactly you would like our library does? I'm not 100% sure to understand your requirement. Our library allows to run code at runtime, so there is some part that makes sense with what you would want to achieve but I'm not sure what you would want us to add, since the calculator part look more like to be on your side.

Best Regards,

Jon
